### ISSUE TITLE
[BUG] Mento trade fails with Ledger Nano X

### ISSUE THREAD

**Issue by joobid** [zviadm/celoterminal#304] opened 2023-08-02 08:01 UTC
**Environment**
Operating System: MacBook Pro con Ventura 13.5
Celo Terminal Version: 1.18.2
Ledger version: Nano X firmware 2.2.1

**Describe the bug**
Mento app in Celo Terminal loose connection with Ledger Nano X during a trade.

**To Reproduce**
0. Ledger NanoX with Celo app and enough CELO to trade
1. Connect Ledger Nano X to Celo Terminal
2. Go to Mento app in Celo Terminal
3. Enter CELO amount to convert to cUSD and click on "Trade"
4. Scroll the information on Ledger screen, and you will see a "Ledger device: Can not connect: Make sure your Ledger device is connected, unlocked, and the Celo app is launched". Celo app in Ledger Nano X freezes, and it needs to be restarted.

Screenshots attached.

**Expected behavior**
Trade CELO for cUSD the same way it works with Ledger Nano S.
<img width="1429" alt="Mento trade in Celo Terminal - Step 3" src="https://github.com/zviadm/celoterminal/assets/18470953/613c5f0b-b875-48a9-966e-f4226f855b38">
![Mento trade in Celo Terminal - Step 4 Ledger freeze](https://github.com/zviadm/celoterminal/assets/18470953/3e62a4c7-29dc-4e16-a193-ef30250d2770)
<img width="1429" alt="Mento trade in Celo Terminal - Step 4" src="https://github.com/zviadm/celoterminal/assets/18470953/ffaf1add-2efa-41d5-9920-5c8228aa3e9e">

**Comment by zviadm** [comment] 2023-08-31 18:13
Does your Ledger Nano X work with Celocli? If "Nano S" works but "Nano X" does not, that means the issue is most likely deeper than just with Celo Terminal. 
Either something is wrong with the Nano X itself, OR there might some issue with the core Celo libraries. If you can test it with "celocli", that will narrow down the source of the issue.

**Comment by joobid** [comment] 2023-08-31 18:24
I've tested the same operation in Celo Terminal with a Ledger Nano S and it
worked fine. I didn't test it with celocli, can you share a documentation
link to do it?

**Comment by zviadm** [comment] 2023-09-01 17:29
This is the command line tool (celocli) from core Celo Labs folks: https://docs.celo.org/cli

**Comment by joobid** [comment] 2023-10-11 20:12
Sorry for the delay! I've installed celocli and it seems it works with both
Nano S and Nano X. Do you want me to test anything specific with celocli?

**Comment by zviadm** [comment] 2024-05-15 14:53
I am pretty sure this is related to this: https://github.com/celo-org/developer-tooling/issues/221

**Comment by zviadm** [comment] 2024-05-15 20:52
Closing in favor of this: https://github.com/zviadm/celoterminal/issues/344

**Closed by zviadm** 2024-05-15 20:52 UTC
